### PR TITLE
Expand editor when pressing 'esc' key

### PR DESCRIPTION
**Pull request by pe4cey**

### CODE REVIEW

**Comment by irfannuri** [comment]
There is an issue in Safari. It goes under sidebar sometimes,  when there is at least one frame in the stream
screen shot 2017-04-20 at 18 15 40

**Comment by irfannuri** [comment]
@pe4cey @oskarhane I believe both issues mentioned by Oskar are addressed.

**Comment by oskarhane** [comment]
Great, well done.

I'm sorry to say that I found a new issue with those changes.
Multi-line in normal mode does not grow the new top bar.

oskar4j 2017-04-25 at 20 41 45

**Comment by irfannuri** [comment]
@oskarhane updated, Thanks!

**Comment by oskarhane** [comment]
I fixed a minor scrollbar placement issue and pushed to this branch.

**Comment by irfannuri** [comment]
Thank you @oskarhane . That makes this PR a perfect trio work!

**Pull request merged**
