### PR TITLE
Update ui bundle to 0.11.0

### PR DESCRIPTION
**Pull request by recrwplay**
Updates the ui-bundle to the latest version `0.11.0`.

### CODE REVIEW

**Review by martin-neotech — APPROVED** [review]
Thanks.

**Comment by OskarDamkjaer** [comment]
Could we wait to merge this until we release this afternoon? :)

**Comment by OskarDamkjaer** [comment]
Just saw something else get merged, so no need to wait with this one I guess!

**Review by OskarDamkjaer — APPROVED** [review]

**Comment by OskarDamkjaer** [comment]
@martin-neotech what's the status on this PR?

**Comment by martin-neotech** [comment]
> @martin-neotech what's the status on this PR?

I dont know actually, @recrwplay mentioned something about adding `latest` version to the UI bundle so we dont have to manually update it all the time?

**Comment by martin-neotech** [comment]
code already contains `url: https://s3-eu-west-1.amazonaws.com/static-content.neo4j.com/build/ui-bundle-latest.zip`

**Pull request closed without merging**
