### PR TITLE
Set all db-info scope values to empty if disconnected

### PR DESCRIPTION
**Pull request by eve-bright**

### CODE REVIEW

**Comment by oskarhane** [comment]
Could you rebase this @eve-bright?

**Comment by eve-bright** [comment]
Rebased

**Comment by oskarhane** [comment]
Since a database can have empty labels, types and props, would it make sense to just hide those parts and display a "Not connected" message instead, if the user isn't connected?

**Comment by eve-bright** [comment]
I think we would still want to clear the values to avoid them accidentally appearing when logging in as a different user.

**Comment by oskarhane** [comment]
Sure thing, the change you've done look good.

**Pull request merged**
