### PR TITLE
Allow zoom buttons on small frames (with settings config)

### PR DESCRIPTION
**Pull request by ivnnv**
It seems that by historical reasons (#447) it is intentional to hide the zoom button on non-fullscreen frames., but I think nowadays we have big enough screen to have them visible (in the case the user wants, hence adding a settings option defaulting to false, just as the current behaviour).

So this PR is adding a config checkbox option to have the zoom buttons available and adapts those buttons to make them smaller accordingly.

zoom small frame

PS: CLA sign sent

### CODE REVIEW

**Comment by OskarDamkjaer** [comment]
Thanks for your PR and for signing the CLA! 

I agree we should show the zoom controls more often and I don't even think we'd need to hide it behind a setting. It'd be reasonable to always show them.

Could you keep only the icon size change and remove the setting and the `if (this.props.fullscreen || this.props.zoomOnSmallFrames) {` check?

**Comment by OskarDamkjaer** [comment]
@ivnnv Also, I added you to the allow-list so the CI should run your tests properly now.

**Comment by ivnnv** [comment]
@OskarDamkjaer friendly ping, I reworked the PR to remove the config setting and now all tests have passed and everything seems ready. Excited to have my first contribution merged!

**Comment by OskarDamkjaer** [comment]
@ivnnv Looks great, thanks!

**Pull request merged**
