### PR TITLE
Fix text position in GraphComponent for rtl languages

### PR DESCRIPTION
**Pull request by sadeghpro**
Screen Shot 2020-07-23 at 11 43 39 PM

### CODE REVIEW

**Comment by sadeghpro** [comment]
Hi
How to see build logs?
How to register in teamcity?

**Comment by OskarDamkjaer** [comment]
Hello and thanks for taking the time to send this pull request, stuff like this is really easy to miss! Your build is failing because you've not read and signed our [cla](https://neo4j.com/developer/cla/).

Sadly I have no good way to register outside contributors in teamcity/automatically show build logs, however when running the end to end tests locally (after signing the cla) you should get the same results.

**Comment by sadeghpro** [comment]
Hi, tnx @OskarDamkjaer 
I sign cla yesterday I don't know how long it will take to accept that.
I only test my work with `yarn test`, but after your comment I use `yarn e2e` but it's failed and take so time to fix it, I send another pull request to avoid my mistakes for other

**Comment by OskarDamkjaer** [comment]
I'll rerun the tests now!

**Comment by oskarhane** [comment]
Fixes #1173

**Pull request merged**
