### PR TITLE
Retrieve and present update statistics from bolt result

### PR DESCRIPTION
**Pull request by irfannuri**
- Retrieve query update statistics from bolt result (from summary.counters)
- Prepend update stats to streaming stats in Status Bar
- Present update stats in Body in Table & Ascii View if there are no rows

### CODE REVIEW

**Comment by pe4cey** [comment]
The only issue I noticed was with the types of cypher view available. 

Here we return three views (rows, ascii & code) with the rows and ascii rendering the same thing:
views

In 2.0 we show two views (rows & code):
screen shot 2017-04-24 at 19 09 22

**Comment by irfannuri** [comment]
Thanks @pe4cey, updated.

**Comment by oskarhane** [comment]
Great!

One thing that I found that needs to be addressed:

1. Executing `RETURN rand()` should show a frame with ascii table view available. Just it's just rows + code atm.

**Comment by irfannuri** [comment]
@oskarhane done. I had to rebase btw

**Pull request merged**
