### PR TITLE
Update to Nevada 0.0.176, added integration for saving style data

### PR DESCRIPTION
**Pull request by joknelid**
Not 100% necessary to merge, but pushing to get a build for user testing

### CODE REVIEW

**Comment by pe4cey** [comment]
There is an error thrown when both old and new vis types are rendered in the stream. 
```neo4j-visualization.js:6 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at t.value (neo4j-visualization.js:6)
    at t.value (neo4j-visualization.js:6)
    at t.value (neo4j-visualization.js:6)
    at NevadaWrapper.componentWillReceiveProps (NevadaWrapper.jsx:122)
    at setComponentProps (preact.js:278)
    at buildComponentFromVNode (preact.js:363)
    at idiff (preact.js:180)
    at innerDiffNode (preact.js:231)
    at idiff (preact.js:196)```

**Comment by joknelid** [comment]
I cant get that error, what query/data did you use? 

Btw, is this what you mean by having both new and old vis in the stream?
screen shot 2017-04-13 at 15 23 50

**Comment by pe4cey** [comment]
Yeah that is it. Are you able to execute any cypher once both vis types are in the stream?

**Comment by joknelid** [comment]
Yeah I can keep running queries and adding to the stream. Also tried switching between new and old vis a couple of times so must be something I'm missing

**Comment by joknelid** [comment]
Mark: Error should be fixed now

**Comment by pe4cey** [comment]
@joknelid LGTM

**Pull request merged**
