### PR TITLE
Various small improvements to sysinfo

### PR DESCRIPTION
**Pull request by huboneo**
This PR addresses three requested improvements for `:sysinfo`:
- Add datetime output to frames to show user when information was last updated
- Show Store Size
- Display changes to dbms.cluster.overview

### Screenshots
Cluster
Screenshot 2019-11-21 at 14 32 55
3.x
Screenshot 2019-11-21 at 14 37 09
4.x
Screenshot 2019-11-21 at 14 38 37

### CODE REVIEW

**Comment by huboneo** [comment]
@oskarhane thank you for your feedback. Can you give more detail on the counts? was in in 4.0?

**Comment by huboneo** [comment]
@oskarhane I was unable to reproduce the long loading times in the sidebar on both 3.x and 4.x, can you provide STR?

**Comment by huboneo** [comment]
@oskarhane I have addressed the above issues. please review again

**Comment by oskarhane** [comment]
Also, would you mind updating the description of this PR so it reflects what's going in (not the counts anymore).

**Comment by huboneo** [comment]
@oskarhane I believe we decided not to clarify these for now. I've updated the styling of the status bar!

**Pull request merged**
