### PR TITLE
fixes text color in dark theme

### PR DESCRIPTION
**Pull request by sendilkumarn**
fixes [#7044](https://github.com/neo4j/neo4j/issues/7044)

### CODE REVIEW

**Comment by oskarhane** [comment]
Hi @sendilkumarn, thanks a lot for helping out. In order for me to consider the PR (and our build system to build your PR), we need you to sign our [CLA](https://neo4j.com/developer/cla/).

**Comment by sendilkumarn** [comment]
@oskarhane Is there anything to do apart from sending a mail ?

**Comment by oskarhane** [comment]
@sendilkumarn No, there's a manual step that I have to do so please open this pr again.

**Comment by sendilkumarn** [comment]
@oskarhane I have opened another #236

**Pull request closed without merging**
