### PR TITLE
Listen for config maxFrames and enforce that limit in stream

### PR DESCRIPTION
**Pull request by oskarhane**
Will not affect pinned frames.
I separated the epic tests from reducer tests because I think it gets messy with both of them in the same file.

### CODE REVIEW

**Comment by pe4cey** [comment]
Should this PR cover the visual side of changing the `maxFrames` in settings?

**Comment by oskarhane** [comment]
If we broaden the scope if it, sure 😃

**Comment by oskarhane** [comment]
Added to sidebar @pe4cey

**Comment by pe4cey** [comment]
👍

**Pull request merged**
