### PR TITLE
#584 - Removing max width from data table view

### PR DESCRIPTION
**Pull request by jdorleans**
#584 
- Removing max-width from data table view since it makes really hard to visualise long length strings such as UUIDs and tokens.

### CODE REVIEW

**Comment by oskarhane** [comment]
Thanks for your contribution @jdorleans!
I think we will need some kind of max-width so we don't end up with a huge horizontal scroll that makes the overview and readability even worse.
Please provide some screenshots of before/after for different kinds of outputs (of different lengths).

**Comment by oskarhane** [comment]
Closing this due to inactivity

**Comment by nhooey** [comment]
@jdorleans @oskarhane: Could you guys figure this one out?

Almost a year after this seemingly reasonable fix was proposed, truncated tables remain an issue.

**Comment by oskarhane** [comment]
I have not looked into this anymore @nhooey. If you know of a sustainable fix, feel free to open a PR for it and we will happily accept it.
The proposed fix in this PR did not render nicely for all kinds of output lengths.

**Pull request closed without merging**
