### PR TITLE
Hydrate state

### PR DESCRIPTION
**Pull request by pe4cey**
The PR ensures that when the reducer is loaded that the 'state' gets applied against a known 'initialState'. This makes sure that if we update the 'initialState' that the new key's get stored in the 'state' object.

### CODE REVIEW

**Comment by oskarhane** [comment]
btw, congrats on getting the 400th issue/pr in this repo 😸

**Comment by pe4cey** [comment]
🎉  400th!

I will look in to the localstorage persistance

**Comment by pe4cey** [comment]
@oskarhane Updated

**Comment by oskarhane** [comment]
Could you rebase this?
At this current state you're trying to bring back `src/shared/modules/visualization/visualizationDuck.js` which has been deleted.

**Comment by oskarhane** [comment]
Other than that, lgtm.

**Comment by pe4cey** [comment]
@oskarhane rebased

**Pull request merged**
