### PR TITLE
Style schema frame

### PR DESCRIPTION
**Pull request by irfannuri**
Style schema frame as a preformatted area

### CODE REVIEW

**Comment by pe4cey** [comment]
It all works well but the frame has a lot of white space bellow the `:schema` text. screen shot 2017-04-24 at 18 44 36

**Comment by irfannuri** [comment]
Done @pe4cey, reduced by half

**Comment by oskarhane** [comment]
I think @pe4cey meant the white below the contents.
This is the frame in the old browser: 
oskar4j 2017-04-25 at 10 39 14

And in the new: 
oskar4j 2017-04-25 at 10 40 12

Unless there's some major css-ing that needs to be done, it'd be nice to have a not so tall frame there.

**Comment by pe4cey** [comment]
The core of the styling for the `:schema` frame is complete. Lets move forward and handle the height issue in another PR.

**Pull request merged**
