### PR TITLE
Make sure timeout is cleared properly

### PR DESCRIPTION
**Pull request by OskarDamkjaer**
This is a small PR to prevent the waiting banner from showing even though you're already connected in sandbox. I've added some types and some minor refactoring as well. The problem was not clearing setTimeout properly.

### CODE REVIEW

**Comment by jexp** [comment]
Works now for me, no yellow bars anymore.

**Comment by jharris4** [comment]
@OskarDamkjaer I think we should re-target this to the 4.3-release branch...

**Comment by OskarDamkjaer** [comment]
I'll rebase!

**Comment by jharris4** [comment]
The changes look good to me! I'd just like to be able to reproduce the issue this fixes if possible, so I can verify the fix...

**Review by jharris4 — APPROVED** [review]
This one was impossible to test, but I can see that the change definitely fixes some issues with the initial implementation (missing deps on useEffect hook) so let's merge it!

**Pull request merged**
